# docker-compose.yml
version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: prepwise-backend:latest
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-8000}/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: prepwise-frontend:latest
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_API_URL=${BACKEND_API_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${FRONTEND_PORT:-5000}:5000"
